[package]
name = "briny"
version = "0.7.1"
edition = "2021"
rust-version = "1.89.0"
description = "Low-level enforcement of memory layout integrity"
license = "MIT"
documentation = "https://docs.rs/briny"
keywords = ["security", "efficient", "no_std", "memory", "no_alloc"]
categories = [
    "no-std",
    "embedded",
    "data-structures",
    "memory-management",
    "no-std::no-alloc",
]
repository = "https://github.com/bobbothe2nd/briny"
readme = "README.md"

[dependencies]
half = { version = "2", optional = true, default-features = false }

[features]
half = ["dep:half"]
nightly_float = []
